vich_uploader:
   db_driver: orm

   metadata:
      type: attribute

   mappings:
      products:
         uri_prefix: /images/realEstate
         upload_destination: "%kernel.project_dir%/public/images/realEstate"
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

         delete_on_remove: true
